### Get token
POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "javainuse",
  "password": "password"
}

> {% client.global.set("auth_token", response.body.token); %}

### Request with token -> 200 OK

GET http://localhost:8080/hello
Authorization: Bearer {{auth_token}}

### Request without token -> 401 Unauthorized

GET http://localhost:8080/hello





